apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: cifar10-dist
  namespace: kubeflow-training
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: eyesoncloud/pytorch-cifar10:v5
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              args:
                - "--epochs=1"
                - "--batch-size=32"
                - "--subset-size=2000"
                - "--workers=0"
              resources:
                requests:
                  cpu: "500m"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"

    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: eyesoncloud/pytorch-cifar10:v5
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              args:
                - "--epochs=1"
                - "--batch-size=32"
                - "--subset-size=2000"
                - "--workers=0"
              resources:
                requests:
                  cpu: "500m"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"
