apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: banking-app
spec:
  serviceName: qdrant
  replicas: 1

  selector:
    matchLabels:
      app: qdrant

  template:
    metadata:
      labels:
        app: qdrant

    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant
        ports:
        - containerPort: 6333
        volumeMounts:
        - name: storage
          mountPath: /qdrant/storage

  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: csi-nfs
      resources:
        requests:
          storage: 1Gi
