apiVersion: v1
kind: ConfigMap
metadata:
  name: risk-config
  namespace: bankbot
data:
  OLLAMA_URL: "http://bankbot-llm-ollama:11434"
  MODEL: "qwen2.5:0.5b"
  APP_ENV: "production"
  DATABASE_URL: "postgresql://bankbot:BankBot@123@postgres:5432/bankbot"
