apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.100.11   # Replace with your NFS server IP or service DNS
  share: /srv/nfs/kubedata
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
